### ISSUE TITLE
Internal Server Error thrown when base_price < 9

### ISSUE THREAD

**Issue by nischalhp** [Instamojo/instamojo-py#3]
While using instamojo-py to create an offer and `base_price` was lesser than 9 an internal server error was thrown.

    {"message": "Internal Server Error", "success": false}

However if compulsory fields like `title` and `currency` are missed out or invalid, proper errors are reported in the response. If `base_price` is missing the right error is shown; however if `base_price` < 9 then an internal server error is thrown.

One way to solve this is to add this constraint in the API endpoint documentation.

**Comment by indradhanush** [comment]
Closing, as this is no longer valid.
